defaultPortal: staging
portals:
  - name: staging
    portalId: REPLACE_WITH_STAGING_PORTAL_ID
    authType: personalaccesskey
  - name: production
    portalId: REPLACE_WITH_PRODUCTION_PORTAL_ID
    authType: personalaccesskey
